apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: user-n-device-namespace
spec:
  ports:
     # Inside the cluster, what port does the service expose? 
  - port: 30001 # port which the service internally exposes itself to

    # Which port do pods selected by this service expose?
    targetPort: 30001
    # Which port on the node is the service available through?
    nodePort: 30001
  type: NodePort
  externalIPs: 
     - 35.225.173.197
     - 104.198.186.33
  selector:
    app: rest
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rest
  namespace: user-n-device-namespace
spec:
  selector:
    matchLabels:
      app: rest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - image: samvede/users-n-devices:latest
        name: rest
        imagePullPolicy: Always
        ports:
        - containerPort: 30001
          name: rest
